#!/bin/bash
chown -R nobody:nogroup /mirror
(
	while true; do 
		echo "$(date) Starting rsyncd"
		/usr/bin/rsync --no-detach --daemon --config /etc/rsyncd.conf
		sleep 1
	done
) &
(
	while true; do 
		echo "$(date) Starting httpd"
		/usr/sbin/apache2ctl -k start -D FOREGROUND
		sleep 1
	done
) &

wait
